# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [31]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame

In [32]:
# Load the csv exported in Part I to a DataFrame:
path = "../WeatherPy/Data Sets/clean_city_data.csv"

# Reading csv file to dataframe:
city_dataframe = pd.read_csv(path)

city_dataframe.head()

,City,Country,Latitude,Longitude,Cloudiness,Temperature,Max Temp,Min Temp,Humidity,Wind Speed
0,Bluff,NZ,-46.6000,168.3333,100,52.81,52.81,52.81,58,2.35
1,Ushuaia,AR,-54.8000,-68.3000,20,42.46,42.46,42.46,49,17.27
2,Bredasdorp,ZA,-34.5322,20.0403,12,57.02,57.02,57.02,67,18.19
3,Torbay,CA,47.6666,-52.7314,75,67.19,68.58,65.16,92,23.02
4,Tuktoyaktuk,CA,69.4541,-133.0374,100,55.40,55.40,55.40,94,5.75

### Humidity Heatmap

In [33]:
# Configure gmaps:
gmaps.configure(api_key=g_key)

# Use the Lat and Lng as locations and Humidity as the weight:
locations = city_dataframe[["Latitude","Longitude"]]
humidity = city_dataframe["Humidity"]

In [34]:
#A dd Heatmap layer to map.
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=3)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria

In [35]:
# Create new Dataframe with specific weather criteria:
# Zero clouds:
cloud_dataframe = city_dataframe[city_dataframe["Cloudiness"] == 0 ]

# Max Temp of 80 F but higher than 70 F :
temp_dataframe = cloud_dataframe[(cloud_dataframe["Max Temp"] > 70) & (cloud_dataframe["Max Temp"] < 80)]

# Wind Speed less than 10 mph:
wind_dataframe = temp_dataframe[temp_dataframe["Wind Speed"] < 10]

# Drop any rows with null values
wind_dataframe = wind_dataframe.dropna() 
wind_dataframe

,City,Country,Latitude,Longitude,Cloudiness,Temperature,Max Temp,Min Temp,Humidity,Wind Speed
8,Sirte,LY,31.2089,16.5887,0,78.55,78.55,78.55,63,4.05
20,Hūn,LY,29.1268,15.9477,0,77.52,77.52,77.52,61,6.24
27,Archidona,ES,37.0965,-4.3887,0,66.34,70.66,63.16,66,3.31
45,Vilhena,BR,-12.7406,-60.1458,0,71.29,71.29,71.29,38,2.64
71,Ürümqi,CN,43.8010,87.6005,0,70.75,70.75,70.75,27,2.24
107,Iberia,US,29.9502,-91.7507,0,76.98,78.87,75.97,88,4.61
139,Steamboat Springs,US,40.4850,-106.8317,0,64.89,71.19,55.54,44,6.91
206,Paralímni,CY,35.0375,33.9833,0,77.05,77.14,75.69,86,8.01
241,Bereket,TM,39.2446,55.5154,0,77.40,77.40,77.40,22,7.20
246,Ardakān,IR,32.3100,54.0175,0,74.25,74.25,74.25,13,8.88
250,Slidell,US,30.2752,-89.7812,0,76.51,79.00,74.48,91,3.44
256,Abu Samrah,SY,35.3029,37.1841,0,70.61,70.61,70.61,69,6.42
262,Kiryat Gat,IL,31.6100,34.7642,0,75.16,79.39,74.08,72,5.66
306,Natal,BR,-5.7950,-35.2094,0,73.62,73.62,72.25,88,9.22
347,Changji,CN,44.0167,87.3167,0,74.19,74.19,74.19,27,2.24
353,Zomin,UZ,39.9606,68.3958,0,77.20,77.20,77.20,14,4.97
356,Mayo,US,38.8876,-76.5119,0,71.08,77.18,67.50,87,1.01
378,Tripoli,LY,32.8752,13.1875,0,77.13,77.13,77.13,68,3.06
422,Ţalkhā,EG,31.0539,31.3779,0,74.98,74.98,74.98,84,5.64
438,Niles,US,42.0189,-87.8028,0,69.96,74.89,63.52,72,0.00
492,Mitchell,US,43.7094,-98.0298,0,73.24,73.38,69.75,75,9.22
508,Baharly,TM,38.4362,57.4316,0,78.80,78.80,78.80,19,4.36
510,Awjilah,LY,29.1081,21.2869,0,75.72,75.72,75.72,53,4.50
518,Buşayrā,JO,30.7376,35.6078,0,72.77,72.77,72.77,28,2.06
526,Waddān,LY,29.1614,16.1390,0,76.33,76.33,76.33,63,5.23
527,Gazli,UZ,40.1333,63.4500,0,78.67,78.67,78.67,19,6.04
555,Fort Nelson,CA,58.8053,-122.7002,0,78.39,78.39,78.39,57,0.00

### Hotel Map
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [40]:
# Store dataframe to new variable
hotel_df = wind_dataframe

# Add a "Hotel Name" column to the DataFrame.
hotel_df["Hotel Name"] = ""

#Set paramaters to search for hotels with 5000 meters:
params = {
    "radius": 50000,
    "types": "hotel",
    "keyword": "hotels",
    "key": g_key
}

# Use the lat/lng we recovered to identify airports
for index, row in hotel_df.iterrows():

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Get lat, lng from df:
    lat = row["Latitude"]
    lng = row["Longitude"]

    # Change location each iteration while leaving original params in place:
    params["location"] = f"{lat},{lng}"

    # Make request and print url:
    hotel_data = requests.get(base_url, params=params).json()

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point:
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_data["results"][0]["name"]

    except Exception:
        print("Could not find hotels near", row["City"])
        hotel_df.loc[index,"Hotel Name"] = " "

hotel_df

Could not find hotels near Baharly
Could not find hotels near Gazli

,City,Country,Latitude,Longitude,Cloudiness,Temperature,Max Temp,Min Temp,Humidity,Wind Speed,Hotel Name
8,Sirte,LY,31.2089,16.5887,0,78.55,78.55,78.55,63,4.05,عمارة السلطان للشقق المفروشة
20,Hūn,LY,29.1268,15.9477,0,77.52,77.52,77.52,61,6.24,Al Nakhel Hotel
27,Archidona,ES,37.0965,-4.3887,0,66.34,70.66,63.16,66,3.31,Casa Bambu Resort -Apart Hotel
45,Vilhena,BR,-12.7406,-60.1458,0,71.29,71.29,71.29,38,2.64,Hotel Mirage
71,Ürümqi,CN,43.8010,87.6005,0,70.75,70.75,70.75,27,2.24,Sheraton Urumqi Hotel
107,Iberia,US,29.9502,-91.7507,0,76.98,78.87,75.97,88,4.61,"Holiday Inn & Suites Lafayette North, an IHG H..."
139,Steamboat Springs,US,40.4850,-106.8317,0,64.89,71.19,55.54,44,6.91,Allington Inn & Suites
206,Paralímni,CY,35.0375,33.9833,0,77.05,77.14,75.69,86,8.01,Novel Centre Point Hotel
241,Bereket,TM,39.2446,55.5154,0,77.40,77.40,77.40,22,7.20,Railway motel
246,Ardakān,IR,32.3100,54.0175,0,74.25,74.25,74.25,13,8.88,Hotel
250,Slidell,US,30.2752,-89.7812,0,76.51,79.00,74.48,91,3.44,New Orleans Marriott Metairie at Lakeway
256,Abu Samrah,SY,35.3029,37.1841,0,70.61,70.61,70.61,69,6.42,اخي علاء
262,Kiryat Gat,IL,31.6100,34.7642,0,75.16,79.39,74.08,72,5.66,New Imperial Hotel Jerusalem
306,Natal,BR,-5.7950,-35.2094,0,73.62,73.62,72.25,88,9.22,SERHS Natal Grand Hotel & Resort
347,Changji,CN,44.0167,87.3167,0,74.19,74.19,74.19,27,2.24,Hilton Urumqi
353,Zomin,UZ,39.9606,68.3958,0,77.20,77.20,77.20,14,4.97,Everest Plaza Hotel
356,Mayo,US,38.8876,-76.5119,0,71.08,77.18,67.50,87,1.01,"Holiday Inn Express Cambridge, an IHG Hotel"
378,Tripoli,LY,32.8752,13.1875,0,77.13,77.13,77.13,68,3.06,Radisson Blu Al Mahary Hotel
422,Ţalkhā,EG,31.0539,31.3779,0,74.98,74.98,74.98,84,5.64,Grand Cleopatra Hotel
438,Niles,US,42.0189,-87.8028,0,69.96,74.89,63.52,72,0.00,Ramada by Wyndham Hammond Hotel & Conference C...
492,Mitchell,US,43.7094,-98.0298,0,73.24,73.38,69.75,75,9.22,Comfort Inn & Suites
508,Baharly,TM,38.4362,57.4316,0,78.80,78.80,78.80,19,4.36,
510,Awjilah,LY,29.1081,21.2869,0,75.72,75.72,75.72,53,4.50,إستراحة صلاح الصادق
518,Buşayrā,JO,30.7376,35.6078,0,72.77,72.77,72.77,28,2.06,Mövenpick Petra
526,Waddān,LY,29.1614,16.1390,0,76.33,76.33,76.33,63,5.23,Al Nakhel Hotel
527,Gazli,UZ,40.1333,63.4500,0,78.67,78.67,78.67,19,6.04,
555,Fort Nelson,CA,58.8053,-122.7002,0,78.39,78.39,78.39,57,0.00,Lakeview Inns & Suites - Fort Nelson

In [42]:
#Drop any rows with N/A:
hotel_df = hotel_df[hotel_df["Hotel Name"] != " "]
hotel_df

,City,Country,Latitude,Longitude,Cloudiness,Temperature,Max Temp,Min Temp,Humidity,Wind Speed,Hotel Name
8,Sirte,LY,31.2089,16.5887,0,78.55,78.55,78.55,63,4.05,عمارة السلطان للشقق المفروشة
20,Hūn,LY,29.1268,15.9477,0,77.52,77.52,77.52,61,6.24,Al Nakhel Hotel
27,Archidona,ES,37.0965,-4.3887,0,66.34,70.66,63.16,66,3.31,Casa Bambu Resort -Apart Hotel
45,Vilhena,BR,-12.7406,-60.1458,0,71.29,71.29,71.29,38,2.64,Hotel Mirage
71,Ürümqi,CN,43.8010,87.6005,0,70.75,70.75,70.75,27,2.24,Sheraton Urumqi Hotel
107,Iberia,US,29.9502,-91.7507,0,76.98,78.87,75.97,88,4.61,"Holiday Inn & Suites Lafayette North, an IHG H..."
139,Steamboat Springs,US,40.4850,-106.8317,0,64.89,71.19,55.54,44,6.91,Allington Inn & Suites
206,Paralímni,CY,35.0375,33.9833,0,77.05,77.14,75.69,86,8.01,Novel Centre Point Hotel
241,Bereket,TM,39.2446,55.5154,0,77.40,77.40,77.40,22,7.20,Railway motel
246,Ardakān,IR,32.3100,54.0175,0,74.25,74.25,74.25,13,8.88,Hotel
250,Slidell,US,30.2752,-89.7812,0,76.51,79.00,74.48,91,3.44,New Orleans Marriott Metairie at Lakeway
256,Abu Samrah,SY,35.3029,37.1841,0,70.61,70.61,70.61,69,6.42,اخي علاء
262,Kiryat Gat,IL,31.6100,34.7642,0,75.16,79.39,74.08,72,5.66,New Imperial Hotel Jerusalem
306,Natal,BR,-5.7950,-35.2094,0,73.62,73.62,72.25,88,9.22,SERHS Natal Grand Hotel & Resort
347,Changji,CN,44.0167,87.3167,0,74.19,74.19,74.19,27,2.24,Hilton Urumqi
353,Zomin,UZ,39.9606,68.3958,0,77.20,77.20,77.20,14,4.97,Everest Plaza Hotel
356,Mayo,US,38.8876,-76.5119,0,71.08,77.18,67.50,87,1.01,"Holiday Inn Express Cambridge, an IHG Hotel"
378,Tripoli,LY,32.8752,13.1875,0,77.13,77.13,77.13,68,3.06,Radisson Blu Al Mahary Hotel
422,Ţalkhā,EG,31.0539,31.3779,0,74.98,74.98,74.98,84,5.64,Grand Cleopatra Hotel
438,Niles,US,42.0189,-87.8028,0,69.96,74.89,63.52,72,0.00,Ramada by Wyndham Hammond Hotel & Conference C...
492,Mitchell,US,43.7094,-98.0298,0,73.24,73.38,69.75,75,9.22,Comfort Inn & Suites
510,Awjilah,LY,29.1081,21.2869,0,75.72,75.72,75.72,53,4.50,إستراحة صلاح الصادق
518,Buşayrā,JO,30.7376,35.6078,0,72.77,72.77,72.77,28,2.06,Mövenpick Petra
526,Waddān,LY,29.1614,16.1390,0,76.33,76.33,76.33,63,5.23,Al Nakhel Hotel
555,Fort Nelson,CA,58.8053,-122.7002,0,78.39,78.39,78.39,57,0.00,Lakeview Inns & Suites - Fort Nelson

In [44]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [ ]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Add the layer to the map
fig.add_layer(markers)

# Display figure
fig